# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7583cc359e5d60ff97219ff5d6381eee97a3301024f53803c4c294d13ca60fdca0a38e9b875f2120b7dd46278cc7ba4a4e155267ff9b176fd41d0c956ce1d51

test:
  secret_key_base: cb14e152faf1c361e08e15d158d3280aeba4f64bbcc5f2f56926bce52542b58a46689381ceb52e413a1c318318e1e2a33a123bd34213d04052766f6610923e8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
